apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 585715538481.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 585715538481.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: d881d4b4
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
